<?php

require 'infinitymetrics/orm/om/PersistentBaseUserPeer.php';


/**
 * Skeleton subclass for performing query and update operations on the 'user' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0 on:
 *
 * 11/27/08 02:02:54
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    infinitymetrics/orm
 */
class PersistentUserPeer extends PersistentBaseUserPeer {


} // PersistentUserPeer
