<?php
// This file generated by Propel 1.3.0 convert-props target
// from XML runtime conf file C:\ppm8-dev\app\classes\infinitymetrics\orm\runtime-conf.xml
return array_merge_recursive(array (
  'propel' => 
  array (
    'datasources' => 
    array (
      'infinitymetricsm201' => 
      array (
        'adapter' => 'mysql',
        'connection' => 
        array (
          'dsn' => 'mysql://root:1234@localhost/infinitymetricsm201',
          'user' => 'root',
          'password' => '1234',
        ),
      ),
      'default' => 'infinitymetrics',
    ),
    'generator_version' => '1.3.0',
  ),
), include(dirname(__FILE__) . DIRECTORY_SEPARATOR . 'infinitymetrics-classmap.php'));