<?php
// This file generated by Propel 1.3.0 convert-props target
return array (
  'propel' => 
  array (
    'datasources' => 
    array (
      'infinitymetricsm201' => 
      array (
        'classes' => 
        array (
          'ChannelMapBuilder' => 'infinitymetrics/map/ChannelMapBuilder.php',
          'ChannelPeer' => 'infinitymetrics/ChannelPeer.php',
          'Channel' => 'infinitymetrics/Channel.php',
          'DisputeMapBuilder' => 'infinitymetrics/map/DisputeMapBuilder.php',
          'DisputePeer' => 'infinitymetrics/DisputePeer.php',
          'Dispute' => 'infinitymetrics/Dispute.php',
          'DisputeEntryMapBuilder' => 'infinitymetrics/map/DisputeEntryMapBuilder.php',
          'DisputeEntryPeer' => 'infinitymetrics/DisputeEntryPeer.php',
          'DisputeEntry' => 'infinitymetrics/DisputeEntry.php',
          'EventMapBuilder' => 'infinitymetrics/map/EventMapBuilder.php',
          'EventPeer' => 'infinitymetrics/EventPeer.php',
          'Event' => 'infinitymetrics/Event.php',
          'InstitutionMapBuilder' => 'infinitymetrics/map/InstitutionMapBuilder.php',
          'InstitutionPeer' => 'infinitymetrics/InstitutionPeer.php',
          'Institution' => 'infinitymetrics/Institution.php',
          'InstructorsMapBuilder' => 'infinitymetrics/map/InstructorsMapBuilder.php',
          'InstructorsPeer' => 'infinitymetrics/InstructorsPeer.php',
          'Instructors' => 'infinitymetrics/Instructors.php',
          'ProjectMapBuilder' => 'infinitymetrics/map/ProjectMapBuilder.php',
          'ProjectPeer' => 'infinitymetrics/ProjectPeer.php',
          'Project' => 'infinitymetrics/Project.php',
          'StudentMapBuilder' => 'infinitymetrics/map/StudentMapBuilder.php',
          'StudentPeer' => 'infinitymetrics/StudentPeer.php',
          'Student' => 'infinitymetrics/Student.php',
          'StudentXProjectMapBuilder' => 'infinitymetrics/map/StudentXProjectMapBuilder.php',
          'StudentXProjectPeer' => 'infinitymetrics/StudentXProjectPeer.php',
          'StudentXProject' => 'infinitymetrics/StudentXProject.php',
          'UserMapBuilder' => 'infinitymetrics/map/UserMapBuilder.php',
          'UserPeer' => 'infinitymetrics/UserPeer.php',
          'User' => 'infinitymetrics/User.php',
          'WorkpaceXProjectMapBuilder' => 'infinitymetrics/map/WorkpaceXProjectMapBuilder.php',
          'WorkpaceXProjectPeer' => 'infinitymetrics/WorkpaceXProjectPeer.php',
          'WorkpaceXProject' => 'infinitymetrics/WorkpaceXProject.php',
          'WorkspaceMapBuilder' => 'infinitymetrics/map/WorkspaceMapBuilder.php',
          'WorkspacePeer' => 'infinitymetrics/WorkspacePeer.php',
          'Workspace' => 'infinitymetrics/Workspace.php',
          'WorkspaceShareMapBuilder' => 'infinitymetrics/map/WorkspaceShareMapBuilder.php',
          'WorkspaceSharePeer' => 'infinitymetrics/WorkspaceSharePeer.php',
          'WorkspaceShare' => 'infinitymetrics/WorkspaceShare.php',
        ),
      ),
    ),
  ),
);